@startuml
'https://plantuml.com/sequence-diagram

class Prenda{
    -tipoPrenda:TipoPrenda
    -colorPrimario: Color
    -colorSecundario:Color
    -material:Material
    -Formalidad:Formalidad
    -trama:Enum
    +tipoDePrenda()
    +categoria()
    +material()
}

class Borrador{
    -tipoPrenda:TipoPrenda
    -colorPrimario: Color
    -colorSecundario:Color
    -material:Enum
    -trama:Enum
    +especificarTipoPrenda(TipoPrenda)
    +especificarColorPrimerio(ColorPrimerio)
    +especificarColorSecundario(ColorSecundario)
    +especificarTrama(Trama)
    +especificarMaterial(Material)
}

abstract class Sastre{
+fabricarUniforme()

}

class SastreSanjuan{
+fabricarParteSuperior()
+fabricarParteInferior()
+fabricarCalzado()
}

class Atuendo{
-prendaSuperior:Prenda
-prendaInferior:Prenda
-prendaCalzado:Prenda
}

class Usuario{
-edad:Integer
-motor: MotorSugerencia
-prendas:List<Prenda>
}

abstract class MotorSugerencia{
-estaActivado:Boolean
+generarSugerencias(Usuario)
+filtrarSegunCriterio(Usuario)
}

class MotorAtuendoInformalSenioresMayores{
+generarSugerencias(Usuario)
+filtrarSegunCriterio(Usuario)
}

class MotorAtuendoATemperaturaActual{
-servicioMeteorologico:ServicioMeteorologico
+getTemperaturaActual()
+generarSugerencias(Usuario)
+filtrarSegunCriterio(Usuario)
}

interface ServicioMeteorologico{
+getTemperaturaActual()
}

class ServicioMeteorologicoAccuWeather{
-accuWeatherAPI:AccuWeatherAPI
+getTemperaturaActual()
}

class ServicioMeteorologicoOpenWeather{
-openWeatherApi:OpenWeatherApi
+getTemperaturaActual()
}

class Guardarropa{
-prendas:List<Prenda>
-solicitudesModificacionGuardarropa:List<solicitudesModificacionGuardarropa>
+crearSolicitudAgregarAGuardarropa(Prenda)
+crearSolicitudQuitarDeGuardarropa(Prenda)

}

abstract class SolicitudModificacionGuardarropa{
-Prenda
-Estado
+rechazarSolicitudEn(Guardarropa)
+aceptarSolicitudEn(Guardarropa)
}

class SolicitudAgregarAGuardarropa{
+realizarAccionEn(Guardarropa)
+deshacerAccionEn(Guardarropa)
}

class SolicitudQuitarDeGuardarropa{
+realizarAccionEn(Guardarropa)
+deshacerAccionEn(Guardarropa)
}

SolicitudAgregarAGuardarropa ---|>SolicitudModificacionGuardarropa
SolicitudQuitarDeGuardarropa ---|>SolicitudModificacionGuardarropa
Guardarropa ---> SolicitudModificacionGuardarropa
Usuario --->Guardarropa
Guardarropa--->Prenda
Borrador ...>Prenda
SastreSanjuan ---|>Sastre
Sastre ...>Atuendo
Atuendo --->Prenda
Usuario -->MotorSugerencia
Usuario -->Prenda
MotorAtuendoInformalSenioresMayores ---|>MotorSugerencia
MotorAtuendoATemperaturaActual ---|>MotorSugerencia
MotorAtuendoATemperaturaActual --->ServicioMeteorologico
ServicioMeteorologicoAccuWeather...|>ServicioMeteorologico
ServicioMeteorologicoOpenWeather...|>ServicioMeteorologico

@enduml