@startuml
'https://plantuml.com/sequence-diagram

class Prenda{
    -tipoPrenda:TipoPrenda
    -colorPrimario: Color
    -colorSecundario:Color
    -material:Material
    -Formalidad:Formalidad
    -trama:Enum
    +tipoDePrenda()
    +categoria()
    +material()
}

class Borrador{
    -tipoPrenda:TipoPrenda
    -colorPrimario: Color
    -colorSecundario:Color
    -material:Enum
    -trama:Enum
    +especificarTipoPrenda(TipoPrenda)
    +especificarColorPrimerio(ColorPrimerio)
    +especificarColorSecundario(ColorSecundario)
    +especificarTrama(Trama)
    +especificarMaterial(Material)
}

abstract class Sastre{
+fabricarUniforme()

}

class SastreSanjuan{
+fabricarParteSuperior()
+fabricarParteInferior()
+fabricarCalzado()
}

class Uniforme{
-prendaSuperior:Prenda
-prendaInferior:Prenda
-prendaCalzado:Prenda
}

class Usuario{
-edad:Integer
-motor: MotorSugerencia
}

abstract class MotorSugerencia{
-estaActivado:Boolean
+generarSugerencias(Usuario)
+filtrarSegunCriterio(Usuario)
}

class MotorAtuendoInformalSenioresMayores{
+generarSugerencias(Usuario)
+filtrarSegunCriterio(Usuario)
}

Borrador ...>Prenda
SastreSanjuan ---|>Sastre
Sastre ...>Uniforme
Uniforme --->Prenda
Usuario -->MotorSugerencia
Usuario -->Prenda
MotorAtuendoInformalSenioresMayores ---|>MotorSugerencia
@enduml